# Generated by Django 4.0.3 on 2022-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='describtion',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='title_index'),
        ),
    ]
