# Generated by Django 4.0.3 on 2022-03-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_describtion_alter_book_title_book_title_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='describtion',
            new_name='description',
        ),
    ]
